Scholarship-Portal-main/content/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include, path
from . import  views
from office_file_tracking_system import  settings

app_name='content'

urlpatterns = [
                url(r'^scholarships/$', views.Show_Scholarships, name=''),
                url(r'^scholarships/(?P<s_id>\w+)', views.Scholarship_Detail, name='Scholarship_Detail'),
                path('track_application/', views.Track_Application, name='Track_Application'),
                url('apply/', views.Apply, name='Apply'),
                path('add_scholarship', views.Add_Scholarship, name='Add_Scholarship'),
                path('pending_approvals/', views.Show_Pending_Approvals, name='Show_Pending_Approvals'),
                path('track_student_applications/', views.Track_Student_Applications, name='Track_Student_Applications'),
                # url(r'^pending_approvals/(?P<app_id>\w+)', views.Show_Pending_Approval_Docs, name='Show_Pending_Approval_Docs'),
                path('approve/<str:app_id>', views.Approve, name='Approve'),
                url('approve/', views.Approve, name='Approve'),
                path('reject/', views.Reject, name='Reject'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scholarship-Portal-main/scholarship portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from office_file_tracking_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'content/', include(('content.urls', 'content'), namespace='content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Scholarship-Portal-main/content/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from accounts.models import CustomUser
from django.template.defaultfilters import slugify
from django.utils.text import slugify

def get_pdf_path(instance, filename):
    return 'Attached_files/{0}/pdf/{1}'.format(instance.app_id, filename)


class Application_Count(models.Model):
    app_cnt = models.IntegerField(default=0)

    def __unicode__(self):
        return str(self.app_cnt)


class Scholarship(models.Model):
    name = models.CharField(max_length=255, default='')
    # slug = models.SlugField(max_length=30, unique=True, editable=False)
    abbreviation = models.CharField(max_length=10, default='')
    department = models.ForeignKey('accounts.Department', verbose_name="Department", on_delete=models.CASCADE, blank=True,
                                   null=True)
    requirements_info = models.TextField(default='Requirement information needs to be updated.')
    
    caste = models.CharField(max_length=255, default='NA')
    program = models.CharField(max_length=255, default='NA')
    specialization = models.CharField(max_length=255, default='NA')
    gender = models.CharField(max_length=255, default='NA')
    minimum_cgpa = models.IntegerField(max_length=255, default='0')

    external_link = models.CharField(max_length=1000, default='NA')

    def __str__(self):
        return self.name


class Application(models.Model):
    app_id = models.CharField(max_length=20, primary_key=True)
    request = models.ForeignKey(Scholarship, verbose_name="Request", on_delete=models.CASCADE,default=1)
    applicant = models.ForeignKey(CustomUser, verbose_name="Applicant", on_delete=models.CASCADE,default=1)
    category = models.CharField(max_length=300, default="")
    title = models.CharField(max_length=300, default="")
    department = models.ForeignKey('accounts.Department', verbose_name="Department", on_delete=models.CASCADE, blank=True,
                                   null=True)

    attached_pdf = models.FileField(upload_to=get_pdf_path,
                                   validators=[FileExtensionValidator(["pdf"])],
                                   null=True, blank=True, default=None)

    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    def __unicode__(self):
        return str(self.app_id)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category)
        super(Application, self).save(*args, **kwargs)

Scholarship-Portal-main/content/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.decorators.csrf import csrf_exempt
from content.decorators import login_required_message
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
import datetime
from accounts.models import Department
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.conf import settings

@csrf_exempt
def checkuserifscrutinyuser(user):
    if user.groups.filter(name="owner").exists() and user.is_superuser:
        return True
    else:
        return False

def is_user_eligible(user, sch):
    print(sch.caste, user.caste)
    if(sch.caste != 'NA' and sch.caste != user.caste):
        return False
    print(sch.program, user.program)
    if(sch.program != 'NA' and sch.program != user.program):
        return False
    print(sch.specialization, user.specialization           )
    if(sch.specialization != 'NA' and sch.specialization != user.specialization):
        return False
    print(sch.gender, user.gender)
    if(sch.gender != 'NA'and sch.gender != user.gender):
        return False
    # if(sch.minimum_cgpa != 'NA' && sch.minimum_cgpa != user.minimum_cgpa):
    #     return false
    return True


@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Show_Scholarships(request):
    response = {}
    user = CustomUser.objects.get(pk = request.user.id)
    all_scholarships = Scholarship.objects.all()
    eligible = []
    for sch in all_scholarships:
        if is_user_eligible(user, sch):
            eligible.append(True)
        else:
            eligible.append(False)
            print("ELSE", eligible[-1])
    response['scholarships'] = zip(all_scholarships, eligible)
    return render(request, 'content/all_scholarships.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Scholarship_Detail(request, s_id):
    response = {}
    app = Application.objects.filter(request=s_id, applicant=request.user.id)
    if len(app)>0:
        response['alreadyApplied'] = True
        response['app_id'] = app[0].app_id
        print("IF : ",response['app_id'])
    else:
        response['alreadyApplied'] = False
        response['app_id'] = None
        print("ELSE : ", response['app_id'])

    response['scholarship'] = Scholarship.objects.get(pk=s_id)

    return render(request, 'content/scholarship_detail.html', response)

@csrf_exempt
@login_required(login_url="/login/")
def Apply(request):
    print("APPLIED")
    s_id = request.POST.get('scholarship_id')
    sch = get_object_or_404(Scholarship, id = s_id)
    user_id = request.user.id
    user = get_object_or_404(CustomUser,id=user_id)
    app = Application.objects.filter(request=s_id, applicant=user_id)
    if len(app)>0:
        messages.info(request, "You have already applied to this scholarship")
        new_app = app[0]
    else:
        cnt = Application_Count.objects.get()
        year = datetime.datetime.now().year
        yy = str(year)
        p1 = yy[2:]
        p2 = str(cnt.app_cnt).zfill(4)
        Name = "APP"
        app_id = Name + p1 + p2
        cnt.app_cnt += 1
        cnt.save()
        print(app_id)
        new_app = Application.objects.create(app_id=app_id)
        new_app.department = user.department
        new_app.category = request.POST.get('application_type')
        new_app.applicant = user
        new_app.request = sch
        new_app.title = sch.name
        new_app.is_approved = False
        new_app.attached_pdf = request.FILES.get("up_files", False)
        new_app.department_id = user.department
        new_app.save()
        messages.success(request, "You have successfully applied to this scholarship")

    data = {}
    data['alreadyApplied'] = True
    data['scholarship'] = sch
    response = {}
    response['scholarship'] = sch
    response['app_id'] = new_app.app_id
    return render(request, 'content/scholarship_detail.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Show_Pending_Approvals(request):
    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    return render(request, 'content/show_pending_approvals.html', response)


# @csrf_exempt
# @login_required_message(message="You should be logged in, in order to perform this")
# @login_required(login_url="/login/")
# def Show_Pending_Approval_Docs(request, app_id):
#     response = {}
#     app = Application.objects.filter(app_id=app_id)
#     response['app'] = app[0]
#     print(app[0].attached_pdf)
#     return render(request, 'content/show_documents.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Approve(request, app_id):
    print(app_id)
    app = Application.objects.filter(app_id=app_id)
    if app[0]:
        app = app[0]
    else:
        app = Node
        response = {}
        response['applications'] = applications
        response['departments'] = departments
        return render(request, 'content/show_pending_approvals.html', response)

    app.is_approved = True
    app.is_rejected = False
    app.save()

    to_email = app.applicant.email
    subject = 'Application Status Updated.'
    message = 'Your application has been approved successfully.'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [to_email]
    # send_mail( subject, message, email_from, recipient_list)

    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    return render(request, 'content/show_pending_approvals.html', response)


@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Reject(request):
    app_id = request.POST.get('id_checker')
    reason = request.POST.get('reason')
    app_id = str(app_id).strip()
    print(app_id)
    app = Application.objects.get(pk=app_id)
    
    app.is_approved = False
    app.is_rejected = True

    to_email = app.applicant.email
    subject = 'Application Status Updated.'
    message = 'Your application status has been rejected.\nDue to following reason : \n ' + str(reason)
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [to_email]
    # send_mail(subject, message, email_from, recipient_list)

    app.save()
    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    designations = {'Teacher', 'Faculty Advisor', 'Dean', 'Head of Department', 'Director'}
    response['designations'] = designations
    return render(request, 'content/show_pending_approvals.html', response)


@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Track_Application(request):
    if request.POST:
        app_id = request.POST.get('app_id')
        application = Application.objects.filter(app_id=app_id)
        for a in application:
            print(a.app_id)
        response = {
            'application': application[0],
        }

    else:
        response = {
            'application': None,
        }
    return render(request, 'application/track_application.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Track_Student_Applications(request):
    if request.POST:
        app_id = request.POST.get('app_id')
        application = Application.objects.filter(app_id=app_id)
        for a in application:
            print(a.app_id)
        response = {
            'application': application[0]
        }
    else:
        response = {
            'application': None
        }
    return render(request, 'application/track_application.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Add_Scholarship(request):
    if request.method == "POST":
        user = CustomUser.objects.get(pk=request.user.id)
        response = {}
        sch = Scholarship.objects.create(name = request.POST['title'], abbreviation= request.POST['abbreviation'])
        try:
            dept = Department.objects.get(name=request.POST['department'])
            sch.department = dept[0]
        except Exception as e:
            sch.department = None
        sch.requirements_info = request.POST['requirements_info']
        sch.caste = request.POST['caste']
        sch.program = request.POST['program']
        sch.specialization = request.POST['specialization']
        sch.gender = request.POST['gender']
        if request.POST['minimum_cgpa'] == 'NA':
            sch.minimum_cgpa = 0
        else:
            sch.minimum_cgpa = int(request.POST['minimum_cgpa'])
        sch.external_link = request.POST['external_link']
        sch.save()
        messages.success(request, "Scholarship has been added successfully.")
    if request.user.is_admin:
        return render(request, 'content/add_scholarship.html')
    else:
        return render(request, 'student_home.html')

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")

Scholarship-Portal-main/templates/content/add_scholarship.html
{% extends 'base.html' %}
{% block title %}Home NIT ADDA{% endblock title %}
{% load static %}
{% block content %}
    <head>
        <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    </head>
    <body onload="init()">
    <div class="row main_header">
        <!-- <center><h2><b>Registration</b></h2></center>
         <br>-->
    </div>

    <div class="container" style="min-width:min-content;margin-bottom: 8%">

        <div class=" md-3" style="margin-top:2%;">

            <div class=" sm-3 ">
                <h3 style="text-align:center">Add New Scholarship</h3>
                    <div id="" class="well well-lg">
                    <form method="POST" action="/content/add_scholarship" enctype="multipart/form-data"
                          onsubmit="return validateForm();">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="formText">Scholarship Title *</label>
                            <input class="form-control" name="title" id="title" required>
                        </div>
                        <div class="form-group">
                            <label class="formText">Scholarship Abbreviation *</label>
                            <input class="form-control" name="abbreviation" id="abbreviation" required>
                        </div>
                        <div class="form-group">
                            <label class="formText">Program</label>
                            <input class="form-control" name="program" id="program" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Specialization (if any) </label>
                            <input class="form-control" name="specialization" id="specialization" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Department </label>
                            <input class="form-control" name="department" id="department" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Caste</label>
                            <input class="form-control" name="caste" id="caste" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Requirements Info </label>
                            <input class="form-control" name="requirements_info" id="requirements_info" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Gender</label>
                            <input class="form-control" name="gender" id="gender" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Minimum CGPA</label>
                            <input class="form-control" name="minimum_cgpa" id="minimum_cgpa" >
                        </div>
                        <div class="form-group">
                            <label class="formText">External Link</label>
                            <input class="form-control" name="external_link" id="external_link" >
                        </div>
                        <center>
                            <button type="submit" id="btn"  class="myButton">Add</button>
                        </center>
                    </form>
                    <br>

                </div>
            </div>
        </div>
    </div>

    </body>

    {# Main Section #}
{% endblock content %}

Scholarship-Portal-main/templates/content/all_applied_scholarships.html
{% extends 'base.html' %}
{% block title %}NITW SP{% endblock title %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script src="https://kit.fontawesome.com/57456f662e.js" crossorigin="anonymous"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    </head>
    <body>

        <div class="site-section">
            <div class="container">
                <div>
                    <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">S. No.</th>
                            <th scope="col">Title</th>
                            <th scope="col">Documents</th>
                            <th scope="col">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in user_applications %}
                            <tr>
                                <td style="vertical-align:middle">{{ forloop.counter }}</td>
                                <td style="vertical-align:middle">{{ i.title }}</td>
                                <td  style="vertical-align:middle"><a href="../../media/{{ i.attached_pdf }}">View</a></td>
                                {% if i.is_approved %}
                                    <td style="color:green">Approved</td>
                                {% elif i.is_rejected %}
                                    <td style="color:red">Yes</td>
                                {% else %}
                                    <td style="color:blue">Pending</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>

{% endblock content %}

Scholarship-Portal-main/templates/content/show_documents.html
{% extends 'base.html' %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head xmlns:scrolling="http://www.w3.org/1999/xhtml">
        <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    </head>
    <body>
    <div class="container" style="margin-bottom: 50px">
        {{ app.attached_pdf }}
        <a href="../../media/{{ app.attached_pdf }}">CLICK</a>
        <div class=" md-3" style="margin-top:0.5%;">
            <iframe src="../../media/{{ app.attached_pdf }}#view=FitH&toolbar=0&navpanes=0" frameborder="0"
                    scrolling:"no" style="-webkit-overflow-scrolling: auto;;width: 100%; height: 85%;">
            </iframe>
        </div>
    </div>
    </body>

{% endblock content %}

Scholarship-Portal-main/templates/content/show_pending_approvals.html
{% extends 'base.html' %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script>
            $(document).ready(function () {
                $('select#selectDesignation').change(function () {
                    let optionSelected = $(this).find("option:selected");
                    {#let valueSelected  = optionSelected.val();#}
                    let designation_title = optionSelected.text();
                    console.log("Designation selected is :", designation_title);
                    $.ajax({
                        url: "/accounts/getNames/",
                        type: "POST",
                        data: {'d': designation_title},
                        success: function (names) {
                            $("#selectNames option").remove();
                            $("#selectNames").append("<option selected disabled>Choose Name</option>");
                            for (var i = names.length - 1; i >= 0; i--) {
                                {
                                    console.log(names[i].id + "   ");
                                }
                                $("#selectNames").append("<option value=" + names[i].id + ">" + names[i].first_name+" "+
                                    names[i].last_name+ "</option>");
                            }
                        }
                    });
                });
            });
        </script>
    </head>
    <body>
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success message_container">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ mes }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row main_header" style="text-align: center">
        <h2>All Pending Approvals</h2>
    </div>

    <div class="container" >
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Choose the next Authority to approve.</h4>
                </div>
                <div class="modal-body">
                    <!-- {%  url 'content:Approve' %} -->
                 <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name="id_checker" id="idChecker" value="0">
                        <label class="formText">Select Department</label>
                        <select class="form-control" id="selectDepartment" name="departments" required>
                            <option selected disabled>Choose department</option>
                            {% for department in departments %}
                                <option value="{{ department.id }}">
                                    {{ department.name }}, ({{ department.abbreviation }})
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="formText">Select Designation</label>
                        <select class="form-control" id="selectDesignation" name="roles" required>
                            <option selected disabled>Choose designation</option>
                            {% for designation in designations %}
                                <option value="{{ designation }}">
                                    {{ designation }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="formText">Select Name</label>
                        <select class="form-control" id="selectNames" name="names" required>
                            <option selected disabled>Choose name</option>
                        </select>
                    </div>
                    <center>
                        <button type="submit" id="btn" class="formButton" style="height:40px; width: 120px; padding:0px 10px">Approve and redirect</button>
                    </center>

                 </form>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>

            </div>
          </div>

    <div class="modal fade" id="myModal2" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Please specify the reason to reject.</h4>
                </div>
                <div class="modal-body">
                 <form method="POST" action="{%  url 'content:Reject' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                     <div class="form-group">
                         <input type="hidden" name="id_checker" id="idChecker2" value="0">
                        <label class="formText">Reason</label>
                        <textarea class="form-control" id="reason_textbox" name="reason" required>
                        </textarea>
                    </div>
                    <center>
                        <button type="submit" id="btn" class="formButton" style="height:40px; width: 120px; padding:0px 10px">Reject</button>
                    </center>

                 </form>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>

            </div>
          </div>
        <div>
            <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">S. No.</th>
                    <th scope="col">Application ID</th>
                    <th scope="col">Applicant Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Attached Documents</th>
                    <th scope="col">Actions</th>

                </tr>
                </thead>
                <tbody>

                {% for i in applications %}

                    <tr>
                        <td style="vertical-align:middle">{{ forloop.counter }}</td>
                        <td style="vertical-align:middle; ">{{ i.app_id}}</td>
                        <td style="vertical-align:middle">{{ i.applicant.first_name }} {{ i.applicant.last_name }}</td>
                        <td style="vertical-align:middle">{{ i.title }}</td>
                        {% if i.is_approved %}
                            <td style="vertical-align:middle;color:green">Approved</td>
                        {% elif i.is_rejected %}
                            <td style="vertical-align:middle;color:red">Rejected</td>
                        {% else %}
                        <td style="vertical-align:middle;color:blue">Pending</td>
                        {% endif %}
                        <td style="vertical-align:middle"><a href="../../media/{{ i.attached_pdf }}">View</a></td>
                        {% if user.is_authenticated and user.is_admin %}
                            <td scope="col">
                                    <a id="{{ i.app_id }}" class="btn btn-success"
                                            href="{%  url 'content:Approve' i.app_id %}"
                                        onclick="return approveButtonClicked(this.id)">Approve</a>
                                <a id="{{ i.app_id }}1" class="btn btn-danger"data-toggle="modal" data-target="#myModal2"
                                       onclick="return rejectButtonClicked(this.id)">Reject</a>
                            </td>
                        {% else %}
                            <td style="vertical-align:middle;color:red">N/A</td>
                        {% endif %}

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <script type="text/javascript">
            function approveButtonClicked (appid) {
                console.log("ID=",appid)
                document.getElementById("idChecker").value = appid;
                return true;
            }
            function rejectButtonClicked (appid) {
                console.log("before ID=",appid)
                appid = appid.slice(0, -1)
                console.log("after ID=",appid)
                document.getElementById("idChecker2").value = appid;
                return true;
            }
        </script>
    </body>

{% endblock content %}